apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: fastapi-production
  labels:
    app: fastapi-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/health"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: fastapi-service
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 8000
    targetPort: http
    protocol: TCP
  sessionAffinity: None
---
# Headless service for StatefulSet scenarios or service discovery
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-headless
  namespace: fastapi-production
  labels:
    app: fastapi-service
    component: service
    type: headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: fastapi-service
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
---
# Service Monitor for Prometheus scraping
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-service-monitor
  namespace: fastapi-production
  labels:
    app: fastapi-service
    component: monitoring
spec:
  selector:
    matchLabels:
      app: fastapi-service
      component: service
  namespaceSelector:
    matchNames:
    - fastapi-production
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    relabelings:
    - sourceLabels: [__meta_kubernetes_service_name]
      targetLabel: service_name
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: kubernetes_pod_name