apiVersion: v1
kind: ServiceAccount
metadata:
  name: fastapi-service-account
  namespace: fastapi-production
  labels:
    app: fastapi-service
    component: serviceaccount
  annotations:
    description: "Service account for FastAPI application"
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fastapi-role
  namespace: fastapi-production
  labels:
    app: fastapi-service
    component: rbac
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fastapi-role-binding
  namespace: fastapi-production
  labels:
    app: fastapi-service
    component: rbac
subjects:
- kind: ServiceAccount
  name: fastapi-service-account
  namespace: fastapi-production
roleRef:
  kind: Role
  name: fastapi-role
  apiGroup: rbac.authorization.k8s.io